erDiagram
    doc_unit {
        bigint id PK
        uuid uuid 
        character_varying documentnumber 
        timestamp_with_time_zone creationtimestamp 
        timestamp_with_time_zone fileuploadtimestamp 
        character_varying s3path 
        character_varying filetype 
        character_varying filename 
        character_varying gerichtstyp 
        character_varying vorgang 
        character_varying ecli 
        character_varying spruchkoerper 
        character_varying entscheidungsdatum 
        character_varying gerichtssitz 
        character_varying rechtskraft 
        character_varying eingangsart 
        character_varying dokumentationsstelle 
        character_varying region 
        text entscheidungsname 
        text titelzeile 
        text leitsatz 
        text orientierungssatz 
        text tenor 
        text gruende 
        text tatbestand 
        text entscheidungsgruende 
        bigint document_type_id 
        timestamp_with_time_zone decision_date 
        character_varying data_source 
    }

    norms {
        uuid guid 
        text official_long_title 
        integer id PK
        text official_short_title 
        text official_abbreviation 
        date publication_date 
        date announcement_date 
        text document_type_name 
        text document_norm_category 
        text document_template_name 
        text ris_abbreviation 
        text document_number 
        text document_category 
        date entry_into_force_date 
        character_varying entry_into_force_date_state 
        date principle_entry_into_force_date 
        character_varying principle_entry_into_force_date_state 
        date divergent_entry_into_force_date 
        character_varying divergent_entry_into_force_date_state 
        date expiration_date 
        character_varying expiration_date_state 
        boolean is_expiration_date_temp 
        date principle_expiration_date 
        character_varying principle_expiration_date_state 
        date divergent_expiration_date 
        character_varying divergent_expiration_date_state 
        text expiration_norm_category 
        text print_announcement_gazette 
        text print_announcement_year 
        text print_announcement_number 
        text print_announcement_page 
        text print_announcement_info 
        text print_announcement_explanations 
        text digital_announcement_medium 
        date digital_announcement_date 
        text digital_announcement_edition 
        text digital_announcement_year 
        text digital_announcement_page 
        text digital_announcement_area 
        text digital_announcement_area_number 
        text digital_announcement_info 
        text digital_announcement_explanations 
        text eu_announcement_gazette 
        text eu_announcement_year 
        text eu_announcement_series 
        text eu_announcement_number 
        text eu_announcement_page 
        text eu_announcement_info 
        text eu_announcement_explanations 
        text other_official_announcement 
        text complete_citation 
        text status_note 
        text status_description 
        date status_date 
        text status_reference 
        text repeal_note 
        text repeal_article 
        date repeal_date 
        text repeal_references 
        text reissue_note 
        text reissue_article 
        date reissue_date 
        text reissue_reference 
        text other_status_note 
        text document_status_work_note 
        text document_status_description 
        date document_status_date 
        text document_status_reference 
        date document_status_entry_into_force_date 
        text document_status_proof 
        text document_text_proof 
        text other_document_note 
        text application_scope_area 
        date application_scope_start_date 
        date application_scope_end_date 
        text categorized_reference 
        text other_footnote 
        text digital_evidence_link 
        text digital_evidence_related_data 
        text digital_evidence_external_data_note 
        text digital_evidence_appendix 
        text celex_number 
        text text 
        text entry_into_force_norm_category 
        text footnote_change 
        text footnote_comment 
        text footnote_decision 
        text footnote_state_law 
        text footnote_eu_law 
    }

    keyword {
        bigint id PK
        bigint document_unit_id FK
        text keyword 
    }

    previous_decision {
        bigint id PK
        character_varying court_type 
        character_varying court_location 
        character_varying decision_date 
        character_varying file_number 
        character_varying document_number FK
        bigint document_unit_id FK
        timestamp_with_time_zone decision_date_timestamp 
    }

    previous_decision }o--|| doc_unit : "document_number"
    previous_decision }o--|| doc_unit : "document_unit_id"
    keyword }o--|| doc_unit : "document_unit_id"
