erDiagram
    doc_unit {
        bigint id PK
        uuid uuid 
        character_varying documentnumber 
        timestamp_with_time_zone creationtimestamp 
        timestamp_with_time_zone fileuploadtimestamp 
        character_varying s3path 
        character_varying filetype 
        text entscheidungsgruende 
    }

